# Generated by Django 4.2 on 2023-07-15 06:55

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listing_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='area',
            new_name='area_size',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='address',
            new_name='location',
        ),
        migrations.AddField(
            model_name='listing',
            name='email',
            field=models.EmailField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='mobile_num',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='listing',
            name='plot_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('House', 'House'), ('Flat', 'Flat'), ('Portion', 'Portion'), ('Room', 'Room'), ('Penthouse', 'Penthouse'), ('Farm House', 'Farm House')], max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='purpose',
            field=models.CharField(choices=[('Sell', 'Sell'), ('Rent', 'Rent')], max_length=150, null=True),
        ),
    ]
