# Generated by Django 4.2 on 2023-07-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_account_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(choices=[('Karachi', 'Karachi'), ('Lahore', 'Lahore'), ('Islamabad', 'Islamabad'), ('Faisalabad', 'Faisalabad'), ('Hyderabad', 'Hyderabad'), ('Peshawar', 'Peshawar'), ('Quetta', 'Quetta'), ('Rawalpindi', 'Rawalpindi'), ('Multan', 'Multan'), ('Gujranwala', 'Gujranwala')], max_length=150, null=True),
        ),
    ]
