# Generated by Django 4.2 on 2023-07-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_alter_listing_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='user',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='listing',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
