# Generated by Django 4.2 on 2023-07-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_alter_listing_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='map_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(choices=[('Karachi', 'Karachi'), ('Lahore', 'Lahore'), ('Islamabad', 'Islamabad'), ('Faisalabad', 'Faisalabad'), ('Hyderabad', 'Hyderabad'), ('Peshawar', 'Peshawar'), ('Quetta', 'Quetta'), ('Rawalpindi', 'Rawalpindi'), ('Multan', 'Multan'), ('Gujranwala', 'Gujranwala')], max_length=150, null=True),
        ),
    ]
