# Generated by Django 4.2 on 2023-07-19 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_comment_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterField(
            model_name='listing',
            name='area_size',
            field=models.CharField(choices=[('40', '40'), ('50', '50'), ('60', '60'), ('70', '4'), ('80', '5'), ('90', '6'), ('100', '7+'), ('120', '40'), ('150', '50'), ('200', '60'), ('220', '4'), ('250', '5'), ('300', '6'), ('350', '350'), ('400', '4'), ('420', '5'), ('450', '6'), ('500+', '500')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='num_bathrooms',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7+', '7+')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='num_bedrooms',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7+', '7+')], max_length=2, null=True),
        ),
    ]
