# Generated by Django 4.2 on 2023-07-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_alter_comment_options_alter_listing_area_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area_size',
            field=models.CharField(choices=[('40', '40'), ('50', '50'), ('60', '60'), ('70', '70'), ('80', '80'), ('90', '90'), ('100', '100'), ('120', '120'), ('150', '150'), ('200', '200'), ('220', '220'), ('250', '250'), ('300', '300'), ('350', '350'), ('400', '400'), ('420', '420'), ('450', '450'), ('500+', '500+')], max_length=10, null=True),
        ),
    ]
